// create bikes constant
export const BIKE_CREATE_REQUEST = 'BIKE_CREATE_REQUEST'
export const BIKE_CREATE_SUCCESSFUL = "BIKE_CREATE_SUCCESSFUL"
export const BIKE_CREATE_FAIL = "BIKE_CREATE_FAIL"

//bike fetching
export const BIKES_FETCHING_REQUEST = "BIKES_FETCHING_REQUEST"
export const BIKES_FETCHING_SUCCESSFUL = "BIKES_FETCHING_SUCCESSFUL"
export const BIKES_FETCHING_FAIL = "BIKES_FETCHING_FAIL"

// single bike fetching
export const BIKE_FETCHING_REQUEST = "BIKE_FETCHING_REQUEST"
export const BIKE_FETCHING_SUCCESSFUL = "BIKE_FETCHING_SUCCESSFUL"
export const BIKE_FETCHING_FAIL = "BIKE_FETCHING_FAIL"

// renting the bikes
export const RENT_THE_BIKE = "RENT_THE_BIKE"

// returning the bike details
export const RETURN_THE_BIKE = "RETURN_THE_BIKE"