// ADD TO THE CART
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESSFULL = "ADD_TO_CART_SUCCESSFULL";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

//FEETCHING USERS TRAVELS
export const FETCH_TRAVELS_REQUEST = "FETCH_TRAVELS_REQUEST"
export const FETCH_TRAVELS_SUCCESSFUL = "FETCH_TRAVELS_SUCCESSFUL"
export const FETCH_TRAVELS_FAIL = "FETCH_TRAVELS_FAIL"