export const CREATE_MYRENT_REQUEST = "CREATE_MYRENT_REQUEST"
export const CREATE_MYRENT_SUCCESS = "CREATE_MYRENT_SUCCESS"
export const CREATE_MYRENT_FAIL = "CREATE_MYRENT_FAIL"

// fetching my RentedBikes
export const FETCH_MYRENT_REQUEST = "FETCH_MYRENT_REQUEST"
export const FETCH_MYRENT_SUCCESS = "FETCH_MYRENT_SUCCESS"
export const FETCH_MYRENT_FAIL = "FETCH_MYRENT_FAIL"