// 
export const CREATE_TRAVEL_REQUEST = "CREATE_TRAVEL_REQUEST"
export const CREATE_TRAVEL_SUCCESS = "CREATE_TRAVEL_SUCCESS"
export const CREATE_TRAVEL_FAIL = "CREATE_TRAVEL_FAIL"

// fetching the travels
export const FETCH_TRAVEL_REQUEST = "FETCH_TRAVEL_REQUEST"
export const FETCH_TRAVEL_SUCCESSFULL = "FETCH_TRAVEL_SUCCESSFULL"
export const FETCH_TRAVEL_FAIL = 'FETCH_TRAVEL_FAIL'
